config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  scope "(:locale)" do
    resources :pics
    get 'home/index'
    get 'home/signin'
    get 'home/admin'
    get 'home/near'
    get 'home/search_nearby'

    get "home", to: "home#index", as: "user_root"
    root 'home#index'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :users, only: [ :show, :edit, :update, :index ]
    resources :posts, only: [ :create, :destroy, :new, :edit, :index ]
    get "posts/get_geo"
    get "posts/get_wiki"
    get "posts/get_near_posts"
    get "posts/renew_bounds"
    get "posts/like_post"
    get "posts/like_pic"
    get "posts/:id", to: 'posts#show'
    patch 'posts/:id', controller: 'posts', action: :update
    resources :contributions, only: [ :index, :show, :edit, :new, :update ]
    resources :comments,          only: [:create, :destroy, :index]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    get_and_show_posts
    hot_users
  end

  def siginin
  end

  def admin
    redirect_to root_url unless admin_user?
  end

  def near
    if params[:scale].nil?
      @scale = 1
    else
      @scale = params[:scale].to_i
    end
  end

  def search_nearby

    logger.debug params[:lat]
    logger.debug params[:lon]
    logger.debug params[:scale]
    @latitude  = params[:lat].to_f
    @longitude = params[:lon].to_f
    @scale     = params[:scale].to_i
    @range = 0.002 * @scale
    @nearby_posts = Post.where("latitude>=? AND latitude<?",@latitude-@range,@latitude+@range).where("longitude>=? AND longitude<?",@longitude-@range,@longitude+@range)

    @nearby_hash= Gmaps4rails.build_markers(@nearby_posts) do |post, marker|
      marker.lat post.latitude
      marker.lng post.longitude
      marker.infowindow post.name
      marker.json({title: post.name})
      marker.picture({url: 'http://maps.google.com/mapfiles/ms/icons/blue.png', width: 48, height: 48})
    end
  end

  private
    def get_and_show_posts
      @show_post = Post.paginate(page: params[:page], per_page: 5).order('created_at DESC')
      respond_to do |format|
          format.html
          format.js
      end
    end

    # the logic should be updated
    def hot_users
      @hot_users = User.order("RANDOM()").limit(3).where.not(uid: "1")
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_show_post.html.erb
<%= div_for(show_post, class: "box") do %>
  <%= show_post.name %>
  <%= link_to image_tag(show_post.pics[0].avatar_url), url_for(controller: :posts, action: :show, id: show_post.id) %>
<% end %>

app/views/home/admin.html.erb
<div class="links_for_admin">
  <div id="post_admin">
    <h2>post/index</h2>
      <%= link_to 'posts', posts_path %>
  </div>
  <div id="pic_admin">
    <h2>pic/index</h2>
      <%= link_to 'pics', pics_path %>
  </div>
  <div id="contribution_admin">
    <h2>contribution/index</h2>
      <%= link_to 'contribution', contributions_path %>
  </div>
  <div id="comment_admin">
    <h2>comment/index</h2>
      <%= link_to 'comments', comments_path %>
  </div>
  <div id="user_admin">
    <h2>user/index</h2>
      <%= link_to 'users', users_path %>
  </div>
</div>

app/views/home/index.html.erb
<%= javascript_include_tag 'infinite-scroll' %>
<!-- views/show_post/index.html.erb -->
<div id="content">
  <%= render(partial: 'show_post', collection: @show_post) %>
</div>

<br/>

<% unless @show_post.current_page == @show_post.total_pages %>
  <div class="navigation" id="view-more">
    <%= link_to t('home.index.viewmore'), url_for(page: @show_post.current_page + 1), remote: true, :class => "ui button" %>
  </div>
<% end %>

<div class="ui horizontal list">
  <% @hot_users.each do |hot_user| %>
    <div class="item">
      <% if hot_user.image.thumb.url.nil? %>
        <%= link_to gravatar_for(hot_user), url_for(controller: :users, action: :show, id: hot_user.id), :class => "ui circular image" %>
      <% else %>
        <%= link_to image_tag(hot_user.image.thumb.url), url_for(controller: :users, action: :show, id: hot_user.id), :class => "ui circular image" %>
      <% end %>
      <div class="user-info">
        <div class="ui sub header"><%= hot_user.nickname %></div> <%= hot_user.sum_point %></div>
    </div>
  <% end %>
</div>

app/views/home/index.js.erb
// views/home/index.js.erb
$('#content').append("<%=j render(partial: 'show_post', collection: @show_post, format: 'html') %>").imagesLoaded( function() {
  $('#content').masonry('reload');
});

<% if @show_post.current_page == @show_post.total_pages %>
  $('#view-more').remove();
<% else %>
  $('#view-more a').attr('href', '<%= url_for(page: @show_post.current_page + 1) %>');
<% end %>

app/views/home/near.html.erb
<%= javascript_include_tag 'current-position' %>

<%= link_to 'wider range', controller: 'home', action: 'near',
            scale: @scale+1 %>
<div id="nearby_map" style='width: 800px; height: 400px;'></div>>
<div id="nearby_posts"></div>

app/views/home/search_nearby.js.erb
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'nearby_map'}}, function(){
  markers = handler.addMarkers(<%=raw @nearby_hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(<%= 19 - @scale %>);
});
$('#nearby_posts').append("<%=j render(partial: 'show_post', collection: @nearby_posts, format: 'html') %>")

app/views/home/signin.html.erb
<br>
<br>
<br>
<div class="signin_check">
<% if user_signed_in? %>
  <% if current_user.provider == "facebook" %>
    <i class="facebook icon"></i>
  <% elsif current_user.provider == "twitter" %>
    <i class="twitter icon"></i>
  <% elsif current_user.provider == "google_oauth2" %>
    <i class="google plus icon"></i>
  <% elsif current_user.provider == "instagram" %>
    <i class="instagram icon"></i>
  <% end %>
  <%= link_to current_user.nickname, current_user %>
<% else %>

  <%= t('home.signin.login_message') %>
  <div id="fw-login-button">
    <%= link_to '<i class="facebook icon"></i> Facebook'.html_safe, user_facebook_omniauth_authorize_path,  :class => "ui left floated facebook button" %>
  </div>

  <div id="tw-login-button">
    <%= link_to '<i class="twitter icon"></i> Twitter'.html_safe, user_twitter_omniauth_authorize_path,   :class => "ui left floated twitter button" %>
  </div>

  <div id="google-login-button">
    <%= link_to '<i class="google plus icon"></i> Google'.html_safe, user_google_oauth2_omniauth_authorize_path,   :class => "ui left floated google plus button" %>
  </div>

  <div id="instagram-login-button">
    <%= link_to '<i class="instagram icon"></i> Instagram'.html_safe, user_instagram_omniauth_authorize_path,   :class => "ui instagram button" %>
  </div>
<% end %>
</div>


<div class="signin_merit">
  <h1><%= t('home.signin.merit_title') %></h1>
  <h3><%= t('home.signin.merit1') %></h3>
  <div class="ui section divider"></div>
  <h3><%= t('home.signin.merit2') %></h3>
  <div class="ui section divider"></div>
  <h3><%= t('home.signin.merit3') %></h3>
  <div class="ui section divider"></div>
  <h3><%= t('home.signin.merit4') %></h3>

</div>