config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  scope "(:locale)" do
    resources :pics
    get 'home/index'
    get 'home/signin'
    get 'home/admin'
    get 'home/near'
    get 'home/search_nearby'

    get "home", to: "home#index", as: "user_root"
    root 'home#index'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :users, only: [ :show, :edit, :update, :index ]
    resources :posts, only: [ :create, :destroy, :new, :edit, :index ]
    get "posts/get_geo"
    get "posts/get_wiki"
    get "posts/get_near_posts"
    get "posts/renew_bounds"
    get "posts/like_post"
    get "posts/like_pic"
    get "posts/:id", to: 'posts#show'
    patch 'posts/:id', controller: 'posts', action: :update
    resources :contributions, only: [ :index, :show, :edit, :new, :update ]
    resources :comments,          only: [:create, :destroy, :index]
  end
end

app/models/contribution.rb
class Contribution < ApplicationRecord
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  before_action :set_contribution, only: [:show, :edit, :update, :destroy]

  # GET /contributions
  # GET /contributions.json
  def index
    redirect_to root_url unless admin_user?
    @contributions = Contribution.all
    @show_edit = show_edit?
  end

  # GET /contributions/1
  # GET /contributions/1.json
  def show
    @show_edit = show_edit?
  end

  # GET /contributions/new
  def new
    @contribution = Contribution.new
  end

  # GET /contributions/1/edit
  def edit
    if !user_signed_in? || current_user.id != Settings.root.user_id
      redirect_to contributions_path
    end
  end

  # POST /contributions
  # POST /contributions.json
  def create
    @contribution = Contribution.new(contribution_params)

    respond_to do |format|
      if @contribution.save
        format.html { redirect_to @contribution, notice: 'Contribution was successfully created.' }
        format.json { render :show, status: :created, location: @contribution }
      else
        format.html { render :new }
        format.json { render json: @contribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contributions/1
  # PATCH/PUT /contributions/1.json
  def update
    respond_to do |format|
      if @contribution.update(contribution_params)
        format.html { redirect_to @contribution, notice: 'Contribution was successfully updated.' }
        format.json { render :show, status: :ok, location: @contribution }
      else
        format.html { render :edit }
        format.json { render json: @contribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contributions/1
  # DELETE /contributions/1.json
  def destroy
    @contribution.destroy
    respond_to do |format|
      format.html { redirect_to contributions_url, notice: 'Contribution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contribution
      @contribution = Contribution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contribution_params
      params.require(:contribution).permit(:user_id, :post_id, :diff, :point)
    end

    def show_edit?
      return true if user_signed_in? && current_user.id == Settings.root.user_id
	  return false
    end

end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/views/contributions/_form.html.erb
<%= form_for(contribution) do |f| %>
  <% if contribution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contribution.errors.count, "error") %> prohibited this contribution from being saved:</h2>

      <ul>
      <% contribution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :post_id %>
    <%= f.number_field :post_id %>
  </div>

  <div class="field">
    <%= f.label :diff %>
    <%= f.text_field :diff %>
  </div>

  <div class="field">
    <%= f.label :point %>
    <%= f.number_field :point %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contributions/edit.html.erb
<h1>Editing Contribution</h1>

<%= render 'form', contribution: @contribution %>

<%= link_to 'Show', @contribution %> |
<%= link_to 'Back', contributions_path %>

app/views/contributions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contributions</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Post</th>
      <th>Diff</th>
      <th>Points</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @contributions.each do |contribution| %>
      <tr>
        <td><%= contribution.user_id %></td>
        <td><%= contribution.post_id %></td>
        <td><%= contribution.diff %></td>
        <td><%= contribution.point %></td>
        <td><%= link_to 'Show', contribution %></td>
        <% if @show_edit %>
          <td><%= link_to 'Edit', edit_contribution_path(contribution) %></td>
        <% end %>
        <td><%= link_to 'Destroy', contribution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contribution', new_contribution_path %>

app/views/contributions/new.html.erb
<h1>New Contribution</h1>

<%= render 'form', contribution: @contribution %>

<%= link_to 'Back', contributions_path %>

app/views/contributions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @contribution.user_id %>
</p>

<p>
  <strong>Post:</strong>
  <%= @contribution.post_id %>
</p>

<p>
  <strong>Diff:</strong>
  <%= @contribution.diff %>
</p>

<p>
  <strong>Point:</strong>
  <%= @contribution.point %>
</p>

<% if @show_edit %>
  <%= link_to 'Edit', edit_contribution_path(@contribution) %> |
<% end %>
<%= link_to 'Back', contributions_path %>