config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  scope "(:locale)" do
    resources :pics
    get 'home/index'
    get 'home/signin'
    get 'home/admin'
    get 'home/near'
    get 'home/search_nearby'

    get "home", to: "home#index", as: "user_root"
    root 'home#index'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :users, only: [ :show, :edit, :update, :index ]
    resources :posts, only: [ :create, :destroy, :new, :edit, :index ]
    get "posts/get_geo"
    get "posts/get_wiki"
    get "posts/get_near_posts"
    get "posts/renew_bounds"
    get "posts/like_post"
    get "posts/like_pic"
    get "posts/:id", to: 'posts#show'
    patch 'posts/:id', controller: 'posts', action: :update
    resources :contributions, only: [ :index, :show, :edit, :new, :update ]
    resources :comments,          only: [:create, :destroy, :index]
  end
end

app/views/layouts/_bottom_menu.html.erb
<div class="ui bottom fixed menu">
  <%= link_to t('home.index.title'), root_path, :class => "active item" %>
  <%= link_to t('home.index.post_link'), new_post_path, :class => "item" %>

  <% if user_signed_in? %>
    <div class="item">
      <% if current_user.provider == "facebook" %>
        <i class="facebook icon"></i>
      <% elsif current_user.provider == "twitter" %>
        <i class="twitter icon"></i>
      <% elsif current_user.provider == "google_oauth2" %>
        <i class="google plus icon"></i>
      <% elsif current_user.provider == "instagram" %>
        <i class="instagram icon"></i>
      <% end %>
      <%= link_to current_user.nickname, current_user %>
      [<%= link_to 'Sign out', destroy_user_session_path, method: :delete  %>]
    </div>
  <% else %>
    <%= link_to t('home.index.signin'), home_signin_path, :class => "item" %>
  <% end %>
  <%= link_to t('home.index.nearposts'), home_near_path, :class => "item" %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  Copyright © dauzau-go.pics All Rights Reserved.
  </small>
  <nav>
    <ul>
      <li><%= link_to t('home.footer.rule'), '#' %></li>
      <li><%= link_to t('home.footer.contact'), 'https://twitter.com/' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="ui top fixed menu">
  <%= link_to t('home.index.title'), root_path, :class => "active item" %>

  <div class="right menu">
    <% if user_signed_in? %>
      <div class="point"><%= link_to current_user.sum_point, current_user %> <%= t('home.index.point') %></div>
    <% end %>
    <div class="ui language dropdown right floating icon item" id="languages" data-content="Select Language">
      <i class="world icon"></i>
      <div class="menu">
        <%= link_to_if params[:locale].present?, '日本語',   url_for(controller: controller.controller_name, action: controller.action_name, locale: ''),   :class => "item" %>
        <%= link_to_if params[:locale] != 'en',  'English',  url_for(controller: controller.controller_name, action: controller.action_name, locale: 'en'), :class => "item" %>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GMAP_KEY']}"%>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
  </head>

  <body>
    <div id="notify">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>

    <%= render 'layouts/header' %>

    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>

    <%= render 'layouts/bottom_menu' %>
  </body>
</html>